---
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - 2.6.1
services:
  - postgresql
sudo: required
addons:
  chrome: stable
  postgresql: "9.6"
  apt:
    packages:
      - google-chrome-stable
      - chromium-chromedriver
before_install:
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - yarn install
  - bundle exec rake db:setup db:structure:load
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
env:
  - ADMIN_EMAIL=your.email@example.com
    BASE_URI=localhost:3000
    DURABLE_JWT_CODE=durable-jwt
    FULL_URI=http://localhost:3000
